const english = {
  eyebrow: "TRAVEL MONEY, SIMPLIFIED", intro: "Compare every currency you need in one clear view.", add: "Add currency",
  search: "Search country or currency", popular: "Popular destinations", empty: "No matching destination", remove: "Remove",
  moveUp: "Move up", moveDown: "Move down", install: "Add to home screen", refresh: "Refresh now",
  loading: "Checking the latest rates…", updated: "Updated {time} · Refreshes hourly", cached: "Offline rates · Last updated {time}",
  error: "Rates unavailable. Connect and try again.", notice: "Reference rates only. Card and cash exchange rates may include fees and markup.",
  close: "Close", language: "Page language", selected: "Selected currencies",
};

const localized = {
  ja: ["旅行のお金を、シンプルに", "必要な通貨をひとつの画面ですっきり比較できます。", "通貨を追加", "国名または通貨を検索", "人気の旅行先", "一致する旅行先がありません", "削除", "上へ", "下へ", "ホーム画面に追加", "今すぐ更新", "最新レートを確認中…", "{time}更新・1時間ごとに確認", "オフラインレート・最終更新 {time}", "レートを取得できません。接続後に再試行してください。", "参考レートです。カードや現金の両替には手数料や上乗せが含まれる場合があります。", "閉じる", "ページの言語", "選択した通貨"],
  "zh-TW": ["旅行換匯，更簡單", "在同一個清楚畫面比較所有需要的貨幣。", "新增貨幣", "搜尋國家或貨幣", "熱門目的地", "找不到符合的目的地", "移除", "上移", "下移", "加入主畫面", "立即更新", "正在取得最新匯率…", "更新於 {time}・每小時檢查", "離線匯率・最後更新 {time}", "無法取得匯率，請連線後再試。", "僅供參考。刷卡與現金兌換可能包含手續費及加價。", "關閉", "頁面語言", "已選貨幣"],
  "zh-CN": ["旅行换汇，更简单", "在一个清晰页面比较所有需要的货币。", "添加货币", "搜索国家或货币", "热门目的地", "没有匹配的目的地", "移除", "上移", "下移", "添加到主屏幕", "立即刷新", "正在获取最新汇率…", "更新于 {time}・每小时检查", "离线汇率・最后更新 {time}", "无法获取汇率，请联网后重试。", "仅供参考。银行卡和现金兑换可能包含手续费及加价。", "关闭", "页面语言", "已选货币"],
  th: ["เงินเที่ยว เข้าใจง่าย", "เปรียบเทียบทุกสกุลเงินที่ต้องการในหน้าจอเดียว", "เพิ่มสกุลเงิน", "ค้นหาประเทศหรือสกุลเงิน", "จุดหมายยอดนิยม", "ไม่พบจุดหมายที่ตรงกัน", "ลบ", "เลื่อนขึ้น", "เลื่อนลง", "เพิ่มไปยังหน้าจอหลัก", "อัปเดตตอนนี้", "กำลังตรวจสอบอัตราล่าสุด…", "อัปเดต {time} · ตรวจสอบทุกชั่วโมง", "อัตราออฟไลน์ · อัปเดตล่าสุด {time}", "ไม่สามารถโหลดอัตราได้ โปรดเชื่อมต่อแล้วลองใหม่", "อัตราอ้างอิงเท่านั้น การ์ดและเงินสดอาจมีค่าธรรมเนียมและส่วนต่าง", "ปิด", "ภาษาของหน้า", "สกุลเงินที่เลือก"],
  vi: ["Tiền du lịch, thật đơn giản", "So sánh mọi loại tiền bạn cần trên một màn hình rõ ràng.", "Thêm tiền tệ", "Tìm quốc gia hoặc tiền tệ", "Điểm đến phổ biến", "Không tìm thấy điểm đến", "Xóa", "Chuyển lên", "Chuyển xuống", "Thêm vào màn hình chính", "Cập nhật ngay", "Đang kiểm tra tỷ giá mới nhất…", "Cập nhật {time} · Làm mới mỗi giờ", "Tỷ giá ngoại tuyến · Cập nhật lần cuối {time}", "Không thể tải tỷ giá. Hãy kết nối và thử lại.", "Chỉ là tỷ giá tham khảo. Thẻ và đổi tiền mặt có thể gồm phí và chênh lệch.", "Đóng", "Ngôn ngữ trang", "Tiền tệ đã chọn"],
  fil: ["Pera sa biyahe, pinasimple", "Ihambing ang lahat ng currency na kailangan mo sa isang malinaw na view.", "Magdagdag ng currency", "Maghanap ng bansa o currency", "Mga sikat na destinasyon", "Walang tugmang destinasyon", "Alisin", "Itaas", "Ibaba", "Idagdag sa home screen", "I-refresh ngayon", "Sinusuri ang pinakabagong rates…", "Na-update {time} · Bawat oras", "Offline rates · Huling update {time}", "Hindi makuha ang rates. Kumonekta at subukan muli.", "Reference rates lamang. Maaaring may fees at markup ang card at cash exchange.", "Isara", "Wika ng pahina", "Napiling currency"],
  ms: ["Wang perjalanan, dipermudah", "Bandingkan semua mata wang yang anda perlukan dalam satu paparan.", "Tambah mata wang", "Cari negara atau mata wang", "Destinasi popular", "Tiada destinasi sepadan", "Buang", "Alih ke atas", "Alih ke bawah", "Tambah ke skrin utama", "Muat semula", "Menyemak kadar terkini…", "Dikemas kini {time} · Setiap jam", "Kadar luar talian · Terakhir {time}", "Kadar tidak tersedia. Sambung dan cuba lagi.", "Kadar rujukan sahaja. Kad dan pertukaran tunai mungkin termasuk fi dan tokokan.", "Tutup", "Bahasa halaman", "Mata wang dipilih"],
  id: ["Uang perjalanan, lebih mudah", "Bandingkan semua mata uang yang Anda perlukan dalam satu tampilan.", "Tambah mata uang", "Cari negara atau mata uang", "Destinasi populer", "Tidak ada destinasi yang cocok", "Hapus", "Pindah ke atas", "Pindah ke bawah", "Tambahkan ke layar utama", "Perbarui sekarang", "Memeriksa kurs terbaru…", "Diperbarui {time} · Setiap jam", "Kurs offline · Terakhir {time}", "Kurs tidak tersedia. Hubungkan dan coba lagi.", "Kurs referensi saja. Kartu dan penukaran tunai dapat mencakup biaya dan markup.", "Tutup", "Bahasa halaman", "Mata uang terpilih"],
  fr: ["L’argent du voyage, simplifié", "Comparez toutes les devises utiles dans une seule vue claire.", "Ajouter une devise", "Rechercher un pays ou une devise", "Destinations populaires", "Aucune destination trouvée", "Supprimer", "Monter", "Descendre", "Ajouter à l’écran d’accueil", "Actualiser", "Vérification des derniers taux…", "Mis à jour {time} · Toutes les heures", "Taux hors ligne · Dernière mise à jour {time}", "Taux indisponibles. Connectez-vous et réessayez.", "Taux indicatifs. Les cartes et bureaux de change peuvent appliquer des frais et une marge.", "Fermer", "Langue de la page", "Devises sélectionnées"],
  de: ["Reisegeld, ganz einfach", "Vergleiche alle benötigten Währungen in einer klaren Ansicht.", "Währung hinzufügen", "Land oder Währung suchen", "Beliebte Reiseziele", "Kein passendes Reiseziel", "Entfernen", "Nach oben", "Nach unten", "Zum Startbildschirm", "Jetzt aktualisieren", "Aktuelle Kurse werden geprüft…", "Aktualisiert {time} · Stündlich", "Offline-Kurse · Zuletzt {time}", "Kurse nicht verfügbar. Verbinden und erneut versuchen.", "Nur Referenzkurse. Bei Karten- und Bargeldwechsel können Gebühren und Aufschläge anfallen.", "Schließen", "Seitensprache", "Ausgewählte Währungen"],
  it: ["Il denaro in viaggio, semplice", "Confronta tutte le valute che ti servono in un’unica schermata.", "Aggiungi valuta", "Cerca paese o valuta", "Destinazioni popolari", "Nessuna destinazione trovata", "Rimuovi", "Sposta su", "Sposta giù", "Aggiungi alla schermata Home", "Aggiorna ora", "Controllo dei tassi più recenti…", "Aggiornato {time} · Ogni ora", "Tassi offline · Ultimo aggiornamento {time}", "Tassi non disponibili. Connettiti e riprova.", "Solo tassi indicativi. Carte e cambio contanti possono includere commissioni e maggiorazioni.", "Chiudi", "Lingua della pagina", "Valute selezionate"],
  es: ["Dinero de viaje, sin complicaciones", "Compara todas las monedas que necesitas en una sola vista.", "Añadir moneda", "Buscar país o moneda", "Destinos populares", "No hay destinos coincidentes", "Eliminar", "Subir", "Bajar", "Añadir a inicio", "Actualizar ahora", "Consultando los últimos tipos…", "Actualizado {time} · Cada hora", "Tipos sin conexión · Última actualización {time}", "Tipos no disponibles. Conéctate e inténtalo de nuevo.", "Tipos de referencia. Las tarjetas y el cambio en efectivo pueden incluir comisiones y márgenes.", "Cerrar", "Idioma de la página", "Monedas seleccionadas"],
  cs: ["Cestovní peníze jednoduše", "Porovnejte všechny potřebné měny v jednom přehledu.", "Přidat měnu", "Hledat zemi nebo měnu", "Oblíbené destinace", "Žádná odpovídající destinace", "Odebrat", "Posunout nahoru", "Posunout dolů", "Přidat na plochu", "Obnovit", "Kontrola nejnovějších kurzů…", "Aktualizováno {time} · Každou hodinu", "Offline kurzy · Naposledy {time}", "Kurzy nejsou dostupné. Připojte se a zkuste to znovu.", "Pouze orientační kurzy. Platby kartou a směna hotovosti mohou zahrnovat poplatky.", "Zavřít", "Jazyk stránky", "Vybrané měny"],
  tr: ["Seyahat parası, kolaylaştırıldı", "İhtiyacınız olan tüm para birimlerini tek ekranda karşılaştırın.", "Para birimi ekle", "Ülke veya para birimi ara", "Popüler destinasyonlar", "Eşleşen destinasyon yok", "Kaldır", "Yukarı taşı", "Aşağı taşı", "Ana ekrana ekle", "Şimdi yenile", "En güncel kurlar kontrol ediliyor…", "{time} güncellendi · Saatlik", "Çevrimdışı kurlar · Son {time}", "Kurlar kullanılamıyor. Bağlanıp tekrar deneyin.", "Yalnızca referans kurlardır. Kart ve nakit döviz işlemleri ücret ve marj içerebilir.", "Kapat", "Sayfa dili", "Seçili para birimleri"],
  ar: ["أموال السفر ببساطة", "قارن كل العملات التي تحتاجها في شاشة واحدة واضحة.", "إضافة عملة", "ابحث عن بلد أو عملة", "وجهات شائعة", "لا توجد وجهة مطابقة", "إزالة", "تحريك لأعلى", "تحريك لأسفل", "إضافة إلى الشاشة الرئيسية", "تحديث الآن", "جارٍ التحقق من أحدث الأسعار…", "تم التحديث {time} · كل ساعة", "أسعار دون اتصال · آخر تحديث {time}", "الأسعار غير متاحة. اتصل وحاول مجددًا.", "أسعار مرجعية فقط. قد تشمل أسعار البطاقات والصرف النقدي رسومًا وهوامش.", "إغلاق", "لغة الصفحة", "العملات المختارة"],
};

const keys = ["eyebrow", "intro", "add", "search", "popular", "empty", "remove", "moveUp", "moveDown", "install", "refresh", "loading", "updated", "cached", "error", "notice", "close", "language", "selected"];

export function messages(locale = "en") {
  const key = localized[locale] ? locale : locale.split("-")[0];
  const values = localized[key];
  return values ? { ...english, ...Object.fromEntries(keys.map((name, index) => [name, values[index]])) } : english;
}

export function interpolate(template, values) {
  return template.replace(/\{(\w+)\}/g, (_, key) => values[key] ?? "");
}
